### PR TITLE
feat: added typings

### LINKED ISSUE #14: Supply typescript definitions or js object alternative
I'm trying to get the possible event names that can be used in vue test utils.

Would it be possible to supply a declarations file https://github.com/search?q=json+to+ts
and/or
a js object from the json?

### PR DESCRIPTION
**Pull request by nandi95**
Currently all events have their bubbles and cancellable set.
Should this shape description in the README.md be updated?

Closes #14

### CODE REVIEW

**Review by eddyerburgh — CHANGES_REQUESTED** [review]
Thanks for the quick turnaround. Can you please remove the yarn.lock file? Also you could update the README like you suggested if you have time

**Comment by nandi95** [comment]
No problem, done 👍

**Review by eddyerburgh — APPROVED** [review]
LGTM, thanks for adding TS types!

**Comment by eddyerburgh** [comment]
Side note: It would be great to add them to the scrape.js script—that way they won't get outdated when/if I generate the event objects again. I'll add this as a TODO

**Comment by eddyerburgh** [comment]
Published in 1.1.0

**Pull request merged**
